name: Terraform Modules CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-all-terraform:
    name: Validate Terraform in modules and resources
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.10.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TFLint
        run: |
          apk add --no-cache curl bash git unzip
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

      - name: Scan Terraform directories
        shell: bash
        run: |
          set -e

          for base in modules resources; do
            for dir in $base/*/; do
              echo "Validating Terraform in $dir"

              echo "Checking formatting..."
              terraform -chdir=$dir fmt -check -recursive

              echo "Initializing..."
              terraform -chdir=$dir init -backend=false

              echo "Validating..."
              terraform -chdir=$dir validate

              echo "Running TFLint..."
              cd $dir
              tflint --init || true
              tflint || true
              cd - > /dev/null

              echo "Running Terraform plan with dummy variable..."
              echo 'variable "dummy" { default = "value" }' > $dir/dummy.tf
              terraform -chdir=$dir plan -var="dummy=value"

              echo "Finished processing $dir"
            done
          done
